// AUTO-GENERATED by emit-sdk — do not edit.
// Source: plugin.json `action_types`. Run: just gen-plugins

package main

import shared "github.com/branchkit/plugin-sdk-go"

// GreetParams is the params shape for action "helloworld.greet (Greet)".
type GreetParams struct {
	Name *string `json:"name,omitempty"`
}

// HandleGreet registers a typed handler for action "helloworld.greet (Greet)".
func HandleGreet(p *shared.Plugin, fn func(GreetParams, *shared.OnActionRequest) (any, error)) {
	shared.HandleActionTyped(p, "helloworld.greet", fn)
}
