// AUTO-GENERATED by branchkit-cli dev init — regenerate with: branchkit-gen --plugin .

package main

// GreetParams is the params shape for action "helloworld.greet (Greet)".
type GreetParams struct {
	Name *string `json:"name,omitempty"`
}
